// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJnsIlH-2kQXFJTGWh7H0xmxorXbRPLfg',
    appId: '1:520748422067:web:2f8cf81d4742def13bf1c6',
    messagingSenderId: '520748422067',
    projectId: 'hood-politix-bc574',
    authDomain: 'hood-politix-bc574.firebaseapp.com',
    databaseURL: 'https://hood-politix-bc574-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hood-politix-bc574.firebasestorage.app',
    measurementId: 'G-8Z3KX3GE4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT1QJG189sv2w5S5fg8JmVpdAKMl_6_RY',
    appId: '1:520748422067:android:c387c438a69f89323bf1c6',
    messagingSenderId: '520748422067',
    projectId: 'hood-politix-bc574',
    databaseURL: 'https://hood-politix-bc574-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hood-politix-bc574.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn8VTkAPZ9p2KhiYcymYl9VkoAaXmRFBU',
    appId: '1:520748422067:ios:aef016874406640d3bf1c6',
    messagingSenderId: '520748422067',
    projectId: 'hood-politix-bc574',
    databaseURL: 'https://hood-politix-bc574-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hood-politix-bc574.firebasestorage.app',
    iosBundleId: 'com.hoodpolitix.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
  apiKey: "AIzaSyBOkymauXzpVFjQTTslyb6jd3W_nnu0fD4",
  appId: "1:520748422067:web:8cc3011cafbd72493bf1c6",
  messagingSenderId: "520748422067",
  projectId: "hood-politix-bc574",
  authDomain: "hood-politix-bc574.firebaseapp.com",
  databaseURL: "https://hood-politix-bc574-default-rtdb.europe-west1.firebasedatabase.app", 
  storageBucket: "hood-politix-bc574.appspot.com",  
  measurementId: "G-NMVZ1JH9YK"
  );

}